// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./components/Action.vue')['default']
    AuthorInfo: typeof import('./components/AuthorInfo.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ListBlog: typeof import('./components/ListBlog.vue')['default']
    ListProjects: typeof import('./components/ListProjects.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
